all_maps = [
  # "(2)16-BitLE",
  # "(2)DreamcatcherLE",
  # "(2)LostandFoundLE",
  # "(2)RedshiftLE",
  # "(4)DarknessSanctuaryLE",
  # "AbiogenesisLE",
  # "AbyssalReefLE",
  # "AcidPlantLE",
  # "AcolyteLE",
  # "AcropolisLE",
  # "AscensionToAiurLE",
  # "AutomatonLE",
  # "BackwaterLE",
  # "BattleontheBoardwalkLE",
  # "BelShirVestigeLE",
  # "BlackpinkLE",
  # "BloodBoilLE",
  # "BlueshiftLE",
  # "CactusValleyLE",
  # "CatalystLE",
  # "CeruleanFallLE",
  # "CyberForestLE",
  "DeathAuraLE",
  # "DefendersLandingLE",
  # "DiscoBloodbathLE",
  # "EastwatchLE",
  # "EphemeronLE",
  # "FrostLE",
  # "HonorGroundsLE",
  # "InterloperLE",
  "JagannathaLE",
  # "KairosJunctionLE",
  # "KingsCoveLE",
  "LightshadeLE",
  # "MechDepotLE",
  # "NeonVioletSquareLE",
  # "NewkirkPrecinctTE",
  # "NewRepugnancyLE",
  # "OdysseyLE",
  "OxideLE",
  # "PaladinoTerminalLE",
  # "ParaSiteLE",
  "PillarsOfGoldLE",
  # "PortAleksanderLE",
  # "ProximaStationLE",
  "RomanticideLE",
  # "SequencerLE",
  # "StasisLE",
  "SubmarineLE",
  # "ThunderbirdLE",
  # "TritonLE",
  # "TurboCruise'84LE",
  # "WintersGateLE",
  # "WorldofSleepersLE"
]
