filebeat.inputs:
- type: log
  paths:
    - /var/log/sc2.log
  json:
    keys_under_root: true
    overwrite_keys: true
    message_key: 'message'

output.elasticsearch:
  hosts: ["http://es01:9200"]

processors:
  - decode_json_fields:
      fields: ['message']
      target: json
